// user
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERR = "AUTH_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_TIMELINE = "GET_TIMELINE";
export const UPDATE_TAB = "UPDATE_TAB";
// errors
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// viewedUser
export const GET_VIEWED_USER = "GET_VIEWEDEDUSER";
export const VIEWED_USER_LOADING = "VIEWED_USER_LOADING";
export const VIEWED_USER_LOADED = "VIEWED_USER_LOADED";
export const GET_FRIEND_STATUS = "GET_FRIEND_STATUS";
export const MY_PROFILE = "MY_PROFILE";
export const GET_FRIENDS_INFO = "GET_FRIENDS_INFO";
export const GET_POSTS = "GET_POSTS";
// conversations
export const ACTIVE_CONVERSATION = "ACTIVE_CONVERSATION";
export const CLOSE_CONVERSATION = "CLOSE_CONVERSATION";
export const USER_CONVERSATIONS = "USER_CONVERSATIONS";
export const SECOND_USER = "SECOND_USER";
export const CREATE_CONVERSATION = "CREATE_CONVERSATION";
export const UPDATE_SEARCHCARD = "UPDATE_SEARCHCARD";
